### ISSUE TITLE
Configure GitHub Workflow with tests

### ISSUE THREAD

**Issue by DanielBrito** [DanielBrito/poemix#73]
Test application in the CI/CD pipeline before publishing.

```yaml
# Example of test.yaml to save in .github/workflows

name: Lint and Test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.17.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Lint
        run: yarn run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.17.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn run test
```
